# Generated by Django 4.2.1 on 2023-06-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_publishedmanager"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PublishedManager",
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=250, unique_for_date="published_at"),
        ),
    ]
